@echo off
title Lost Legacy
color E
echo Compiling with Carson...
"C:\Program Files (x86)\Java\jdk1.7.0_07\bin\javac.exe" -classpath deps/GTLVote.jar;deps/log4j-1.2.15.jar;deps/jython.jar;deps/xstream.jar;deps/mina.jar;deps/mysql.jar;deps/poi.jar;deps/slf4j.jar;deps/slf4j-nop.jar -d bin src\server\model\content\*.java src\server\model\controlpanel\*.java src\server\event\*.java src\server\model\items\*.java src\server\model\minigames\*.java src\server\model\npcs\*.java src\server\model\objects\*.java src\server\model\players\*.java src\server\model\players\packets\*.java src\server\model\shops\*.java src\server\net\*.java src\server\task\*.java src\server\util\*.java src\server\world\*.java src\server\util\log\*.java src\server\*.java src\server\world\map\*.java src\server\event\impl\*.java src\server\task\impl\*.java src\server\model\skills\*.java src\server\model\skills\agility\*.java src\server\model\skills\cooking\*.java src\server\model\skills\crafting\*.java src\server\model\skills\farming\*.java src\server\model\skills\firemaking\*.java src\server\model\skills\fishing\*.java src\server\model\skills\fletching\*.java src\server\model\skills\herblore\*.java src\server\model\skills\prayer\*.java src\server\model\skills\mining\*.java src\server\model\skills\runecrafting\*.java src\server\model\skills\slayer\*.java src\server\model\skills\thieving\*.java src\server\model\skills\woodcutting\*.java src\server\model\skills\smithing\*.java src\server\model\players\packets\item\*.java src\server\model\players\packets\bank\*.java src\server\model\players\packets\clicking\*.java src\server\model\players\combat\*.java
echo Compiling with Anthony/VPS...
"C:\Program Files\Java\jdk1.7.0_25\bin\javac.exe" -classpath deps/GTLVote.jar;deps/log4j-1.2.15.jar;deps/jython.jar;deps/xstream.jar;deps/mina.jar;deps/mysql.jar;deps/poi.jar;deps/slf4j.jar;deps/slf4j-nop.jar -d bin src\server\model\content\*.java src\server\model\controlpanel\*.java src\server\event\*.java src\server\model\items\*.java src\server\model\minigames\*.java src\server\model\npcs\*.java src\server\model\objects\*.java src\server\model\players\*.java src\server\model\players\packets\*.java src\server\model\shops\*.java src\server\net\*.java src\server\task\*.java src\server\util\*.java src\server\world\*.java src\server\util\log\*.java src\server\*.java src\server\world\map\*.java src\server\event\impl\*.java src\server\task\impl\*.java src\server\model\skills\*.java src\server\model\skills\agility\*.java src\server\model\skills\cooking\*.java src\server\model\skills\crafting\*.java src\server\model\skills\farming\*.java src\server\model\skills\firemaking\*.java src\server\model\skills\fishing\*.java src\server\model\skills\fletching\*.java src\server\model\skills\herblore\*.java src\server\model\skills\prayer\*.java src\server\model\skills\mining\*.java src\server\model\skills\runecrafting\*.java src\server\model\skills\slayer\*.java src\server\model\skills\thieving\*.java src\server\model\skills\woodcutting\*.java src\server\model\skills\smithing\*.java src\server\model\players\packets\item\*.java src\server\model\players\packets\bank\*.java src\server\model\players\packets\clicking\*.java src\server\model\players\combat\*.java

pause

